### ISSUE TITLE
generate fr and de - 1817

### ISSUE THREAD

**Issue by netapp-gudugunti** [NetAppDocs/astra-control-center-2112#6]
A localization admin will generate the French and German sites. 

### Site maintainers and mergers
Comment in this issue if you update the English site before the issue closes. No other action is required on your part.

**Comment by ntap-bmegan** [comment]
@netapp-rlithman - Why has localization been disabled for this repository? 

https://github.com/orgs/NetAppDocs/repositories?q=astra-control-center-2112&type=all

**Comment by ntap-bmegan** [comment]
Configuration is complete. TOT: 10 min
